-- assets table
ALTER TABLE assets
    ALTER COLUMN purchase_date TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN warranty_start TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN warranty_expire TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN archived_at TYPE TIMESTAMP WITH TIME ZONE;

-- asset_assign table
ALTER TABLE asset_assign
    ALTER COLUMN assigned_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN returned_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN archived_at TYPE TIMESTAMP WITH TIME ZONE;

-- users table
ALTER TABLE users
    ALTER COLUMN archived_at TYPE TIMESTAMP WITH TIME ZONE;

-- user_roles table
ALTER TABLE user_roles
    ALTER COLUMN last_updated_at TYPE TIMESTAMP WITH TIME ZONE;

-- user_type table
ALTER TABLE user_type
    ALTER COLUMN last_updated_at TYPE TIMESTAMP WITH TIME ZONE;


-- laptop_config
ALTER TABLE laptop_config
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN archived_at TYPE TIMESTAMP WITH TIME ZONE;

-- mouse_config
ALTER TABLE mouse_config
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN archived_at TYPE TIMESTAMP WITH TIME ZONE;

-- monitor_config
ALTER TABLE monitor_config
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN archived_at TYPE TIMESTAMP WITH TIME ZONE;

-- hard_disk_config
ALTER TABLE hard_disk_config
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN archived_at TYPE TIMESTAMP WITH TIME ZONE;

-- pendrive_config
ALTER TABLE pendrive_config
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN archived_at TYPE TIMESTAMP WITH TIME ZONE;

-- mobile_config
ALTER TABLE mobile_config
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN archived_at TYPE TIMESTAMP WITH TIME ZONE;

-- sim_config
ALTER TABLE sim_config
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN archived_at TYPE TIMESTAMP WITH TIME ZONE;

-- accessories_config
ALTER TABLE accessories_config
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN archived_at TYPE TIMESTAMP WITH TIME ZONE;
